media: public/media
public_path: /media

content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        default: "Compound Team"
      - name: description
        label: Description
        type: string
        widget: textarea
      - name: cover_image
        label: Cover Image
        type: image
      - name: body
        label: Body
        type: rich-text
